export const TIMEZONES = [
  // UTC
  { value: "UTC", label: "GMT+00:00 UTC" },
  // Americas
  { value: "America/Adak", label: "GMT-10:00 America/Adak" },
  { value: "Pacific/Honolulu", label: "GMT-10:00 Pacific/Honolulu (HST)" },
  { value: "Pacific/Marquesas", label: "GMT-09:30 Pacific/Marquesas" },
  { value: "America/Anchorage", label: "GMT-09:00 America/Anchorage (AKST)" },
  { value: "America/Juneau", label: "GMT-09:00 America/Juneau (AKST)" },
  { value: "America/Metlakatla", label: "GMT-09:00 America/Metlakatla" },
  { value: "America/Nome", label: "GMT-09:00 America/Nome (AKST)" },
  { value: "America/Sitka", label: "GMT-09:00 America/Sitka (AKST)" },
  { value: "America/Yakutat", label: "GMT-09:00 America/Yakutat (AKST)" },
  { value: "America/Los_Angeles", label: "GMT-08:00 America/Los Angeles (PST)" },
  { value: "America/Tijuana", label: "GMT-08:00 America/Tijuana (PST)" },
  { value: "America/Vancouver", label: "GMT-08:00 America/Vancouver (PST)" },
  { value: "America/Boise", label: "GMT-07:00 America/Boise (MST)" },
  { value: "America/Cambridge_Bay", label: "GMT-07:00 America/Cambridge Bay" },
  { value: "America/Creston", label: "GMT-07:00 America/Creston" },
  { value: "America/Dawson", label: "GMT-07:00 America/Dawson" },
  { value: "America/Dawson_Creek", label: "GMT-07:00 America/Dawson Creek" },
  { value: "America/Denver", label: "GMT-07:00 America/Denver (MST)" },
  { value: "America/Edmonton", label: "GMT-07:00 America/Edmonton (MDT)" },
  { value: "America/Fort_Nelson", label: "GMT-07:00 America/Fort Nelson" },
  { value: "America/Hermosillo", label: "GMT-07:00 America/Hermosillo" },
  { value: "America/Inuvik", label: "GMT-07:00 America/Inuvik" },
  { value: "America/Mazatlan", label: "GMT-07:00 America/Mazatlan" },
  { value: "America/Phoenix", label: "GMT-07:00 America/Phoenix (MST)" },
  { value: "America/Whitehorse", label: "GMT-07:00 America/Whitehorse" },
  { value: "America/Yellowknife", label: "GMT-07:00 America/Yellowknife" },
  { value: "America/Chicago", label: "GMT-06:00 America/Chicago (CST)" },
  { value: "America/Guatemala", label: "GMT-06:00 America/Guatemala (CST)" },
  { value: "America/Indiana/Knox", label: "GMT-06:00 America/Indiana/Knox" },
  { value: "America/Indiana/Tell_City", label: "GMT-06:00 America/Indiana/Tell City" },
  { value: "America/Managua", label: "GMT-06:00 America/Managua (CST)" },
  { value: "America/Matamoros", label: "GMT-06:00 America/Matamoros" },
  { value: "America/Menominee", label: "GMT-06:00 America/Menominee" },
  { value: "America/Merida", label: "GMT-06:00 America/Merida (CST)" },
  { value: "America/Mexico_City", label: "GMT-06:00 America/Mexico City (CST)" },
  { value: "America/Monterrey", label: "GMT-06:00 America/Monterrey (CST)" },
  { value: "America/North_Dakota/Beulah", label: "GMT-06:00 America/North Dakota/Beulah" },
  { value: "America/North_Dakota/Center", label: "GMT-06:00 America/North Dakota/Center" },
  { value: "America/North_Dakota/New_Salem", label: "GMT-06:00 America/North Dakota/New Salem" },
  { value: "America/Ojinaga", label: "GMT-06:00 America/Ojinaga" },
  { value: "America/Rainy_River", label: "GMT-06:00 America/Rainy River" },
  { value: "America/Rankin_Inlet", label: "GMT-06:00 America/Rankin Inlet" },
  { value: "America/Regina", label: "GMT-06:00 America/Regina (CST)" },
  { value: "America/Resolute", label: "GMT-06:00 America/Resolute" },
  { value: "America/Swift_Current", label: "GMT-06:00 America/Swift Current" },
  { value: "America/Tegucigalpa", label: "GMT-06:00 America/Tegucigalpa" },
  { value: "America/Winnipeg", label: "GMT-06:00 America/Winnipeg (CST)" },
  { value: "Pacific/Easter", label: "GMT-06:00 Pacific/Easter" },
  { value: "Pacific/Galapagos", label: "GMT-06:00 Pacific/Galapagos" },
  { value: "America/Atikokan", label: "GMT-05:00 America/Atikokan (EST)" },
  { value: "America/Bogota", label: "GMT-05:00 America/Bogota (COT)" },
  { value: "America/Cancun", label: "GMT-05:00 America/Cancun (EST)" },
  { value: "America/Cayman", label: "GMT-05:00 America/Cayman" },
  { value: "America/Detroit", label: "GMT-05:00 America/Detroit (EST)" },
  { value: "America/Eirunepe", label: "GMT-05:00 America/Eirunepe" },
  { value: "America/Guayaquil", label: "GMT-05:00 America/Guayaquil (ECT)" },
  { value: "America/Havana", label: "GMT-05:00 America/Havana (CST)" },
  { value: "America/Indiana/Indianapolis", label: "GMT-05:00 America/Indiana/Indianapolis (EST)" },
  { value: "America/Indiana/Marengo", label: "GMT-05:00 America/Indiana/Marengo" },
  { value: "America/Indiana/Petersburg", label: "GMT-05:00 America/Indiana/Petersburg" },
  { value: "America/Indiana/Vevay", label: "GMT-05:00 America/Indiana/Vevay" },
  { value: "America/Indiana/Vincennes", label: "GMT-05:00 America/Indiana/Vincennes" },
  { value: "America/Indiana/Winamac", label: "GMT-05:00 America/Indiana/Winamac" },
  { value: "America/Iqaluit", label: "GMT-05:00 America/Iqaluit (EST)" },
  { value: "America/Jamaica", label: "GMT-05:00 America/Jamaica (EST)" },
  { value: "America/Kentucky/Louisville", label: "GMT-05:00 America/Kentucky/Louisville (EST)" },
  { value: "America/Kentucky/Monticello", label: "GMT-05:00 America/Kentucky/Monticello (EST)" },
  { value: "America/Lima", label: "GMT-05:00 America/Lima (PET)" },
  { value: "America/Nassau", label: "GMT-05:00 America/Nassau (EST)" },
  { value: "America/New_York", label: "GMT-05:00 America/New York (EST)" },
  { value: "America/Nipigon", label: "GMT-05:00 America/Nipigon" },
  { value: "America/Panama", label: "GMT-05:00 America/Panama (EST)" },
  { value: "America/Pangnirtung", label: "GMT-05:00 America/Pangnirtung" },
  { value: "America/Port-au-Prince", label: "GMT-05:00 America/Port-au-Prince (EST)" },
  { value: "America/Rio_Branco", label: "GMT-05:00 America/Rio Branco" },
  { value: "America/Thunder_Bay", label: "GMT-05:00 America/Thunder Bay (EST)" },
  { value: "America/Toronto", label: "GMT-05:00 America/Toronto (EST)" },
  { value: "America/Anguilla", label: "GMT-04:00 America/Anguilla (AST)" },
  { value: "America/Antigua", label: "GMT-04:00 America/Antigua (AST)" },
  { value: "America/Aruba", label: "GMT-04:00 America/Aruba (AST)" },
  { value: "America/Asuncion", label: "GMT-04:00 America/Asuncion (PYT)" },
  { value: "America/Barbados", label: "GMT-04:00 America/Barbados (AST)" },
  { value: "America/Blanc-Sablon", label: "GMT-04:00 America/Blanc-Sablon (AST)" },
  { value: "America/Boa_Vista", label: "GMT-04:00 America/Boa Vista (AMT)" },
  { value: "America/Campo_Grande", label: "GMT-04:00 America/Campo Grande (AMT)" },
  { value: "America/Caracas", label: "GMT-04:00 America/Caracas (VET)" },
  { value: "America/Cuiaba", label: "GMT-04:00 America/Cuiaba (AMT)" },
  { value: "America/Curacao", label: "GMT-04:00 America/Curacao (AST)" },
  { value: "America/Dominica", label: "GMT-04:00 America/Dominica (AST)" },
  { value: "America/Glace_Bay", label: "GMT-04:00 America/Glace Bay (AST)" },
  { value: "America/Goose_Bay", label: "GMT-04:00 America/Goose Bay (AST)" },
  { value: "America/Grand_Turk", label: "GMT-04:00 America/Grand Turk (EST)" },
  { value: "America/Grenada", label: "GMT-04:00 America/Grenada (AST)" },
  { value: "America/Guadeloupe", label: "GMT-04:00 America/Guadeloupe (AST)" },
  { value: "America/Guyana", label: "GMT-04:00 America/Guyana (GYT)" },
  { value: "America/Halifax", label: "GMT-04:00 America/Halifax (AST)" },
  { value: "America/Kralendijk", label: "GMT-04:00 America/Kralendijk (AST)" },
  { value: "America/La_Paz", label: "GMT-04:00 America/La Paz (BOT)" },
  { value: "America/Lower_Princes", label: "GMT-04:00 America/Lower Princes" },
  { value: "America/Manaus", label: "GMT-04:00 America/Manaus (AMT)" },
  { value: "America/Marigot", label: "GMT-04:00 America/Marigot (AST)" },
  { value: "America/Martinique", label: "GMT-04:00 America/Martinique (AST)" },
  { value: "America/Moncton", label: "GMT-04:00 America/Moncton (AST)" },
  { value: "America/Montserrat", label: "GMT-04:00 America/Montserrat (AST)" },
  { value: "America/Port_of_Spain", label: "GMT-04:00 America/Port of Spain (AST)" },
  { value: "America/Porto_Velho", label: "GMT-04:00 America/Porto Velho (AMT)" },
  { value: "America/Puerto_Rico", label: "GMT-04:00 America/Puerto Rico (AST)" },
  { value: "America/Santiago", label: "GMT-04:00 America/Santiago (CLT)" },
  { value: "America/Santo_Domingo", label: "GMT-04:00 America/Santo Domingo (AST)" },
  { value: "America/St_Barthelemy", label: "GMT-04:00 America/St Barthelemy (AST)" },
  { value: "America/St_Kitts", label: "GMT-04:00 America/St Kitts (AST)" },
  { value: "America/St_Lucia", label: "GMT-04:00 America/St Lucia (AST)" },
  { value: "America/St_Thomas", label: "GMT-04:00 America/St Thomas (AST)" },
  { value: "America/St_Vincent", label: "GMT-04:00 America/St Vincent (AST)" },
  { value: "America/Thule", label: "GMT-04:00 America/Thule (AST)" },
  { value: "America/Tortola", label: "GMT-04:00 America/Tortola (AST)" },
  { value: "America/St_Johns", label: "GMT-03:30 America/St Johns (NST)" },
  { value: "America/Araguaina", label: "GMT-03:00 America/Araguaina (BRT)" },
  { value: "America/Argentina/Buenos_Aires", label: "GMT-03:00 America/Argentina/Buenos Aires (ART)" },
  { value: "America/Argentina/Catamarca", label: "GMT-03:00 America/Argentina/Catamarca" },
  { value: "America/Argentina/Cordoba", label: "GMT-03:00 America/Argentina/Cordoba" },
  { value: "America/Argentina/Jujuy", label: "GMT-03:00 America/Argentina/Jujuy" },
  { value: "America/Argentina/La_Rioja", label: "GMT-03:00 America/Argentina/La Rioja" },
  { value: "America/Argentina/Mendoza", label: "GMT-03:00 America/Argentina/Mendoza" },
  { value: "America/Argentina/Rio_Gallegos", label: "GMT-03:00 America/Argentina/Rio Gallegos" },
  { value: "America/Argentina/Salta", label: "GMT-03:00 America/Argentina/Salta" },
  { value: "America/Argentina/San_Juan", label: "GMT-03:00 America/Argentina/San Juan" },
  { value: "America/Argentina/San_Luis", label: "GMT-03:00 America/Argentina/San Luis" },
  { value: "America/Argentina/Tucuman", label: "GMT-03:00 America/Argentina/Tucuman" },
  { value: "America/Argentina/Ushuaia", label: "GMT-03:00 America/Argentina/Ushuaia" },
  { value: "America/Bahia", label: "GMT-03:00 America/Bahia (BRT)" },
  { value: "America/Belem", label: "GMT-03:00 America/Belem (BRT)" },
  { value: "America/Cayenne", label: "GMT-03:00 America/Cayenne (GFT)" },
  { value: "America/Fortaleza", label: "GMT-03:00 America/Fortaleza (BRT)" },
  { value: "America/Maceio", label: "GMT-03:00 America/Maceio (BRT)" },
  { value: "America/Miquelon", label: "GMT-03:00 America/Miquelon" },
  { value: "America/Montevideo", label: "GMT-03:00 America/Montevideo (UYT)" },
  { value: "America/Paramaribo", label: "GMT-03:00 America/Paramaribo (SRT)" },
  { value: "America/Punta_Arenas", label: "GMT-03:00 America/Punta Arenas" },
  { value: "America/Recife", label: "GMT-03:00 America/Recife (BRT)" },
  { value: "America/Santarem", label: "GMT-03:00 America/Santarem (BRT)" },
  { value: "America/Sao_Paulo", label: "GMT-03:00 America/Sao Paulo (BRT)" },
  { value: "Antarctica/Rothera", label: "GMT-03:00 Antarctica/Rothera" },
  { value: "America/Noronha", label: "GMT-02:00 America/Noronha (FNT)" },
  { value: "America/Scoresbysund", label: "GMT-01:00 America/Scoresbysund" },
  { value: "Atlantic/Azores", label: "GMT-01:00 Atlantic/Azores (AZOT)" },
  { value: "Atlantic/Cape_Verde", label: "GMT-01:00 Atlantic/Cape Verde (CVT)" },
  // Europe/Africa
  { value: "Africa/Abidjan", label: "GMT+00:00 Africa/Abidjan (GMT)" },
  { value: "Africa/Accra", label: "GMT+00:00 Africa/Accra (GMT)" },
  { value: "Africa/Bamako", label: "GMT+00:00 Africa/Bamako (GMT)" },
  { value: "Africa/Banjul", label: "GMT+00:00 Africa/Banjul (GMT)" },
  { value: "Africa/Bissau", label: "GMT+00:00 Africa/Bissau (GMT)" },
  { value: "Africa/Conakry", label: "GMT+00:00 Africa/Conakry (GMT)" },
  { value: "Africa/Dakar", label: "GMT+00:00 Africa/Dakar (GMT)" },
  { value: "Africa/Freetown", label: "GMT+00:00 Africa/Freetown (GMT)" },
  { value: "Africa/Lome", label: "GMT+00:00 Africa/Lome (GMT)" },
  { value: "Africa/Monrovia", label: "GMT+00:00 Africa/Monrovia (GMT)" },
  { value: "Africa/Nouakchott", label: "GMT+00:00 Africa/Nouakchott (GMT)" },
  { value: "Africa/Ouagadougou", label: "GMT+00:00 Africa/Ouagadougou (GMT)" },
  { value: "Africa/Sao_Tome", label: "GMT+00:00 Africa/Sao Tome (GMT)" },
  { value: "Atlantic/Canary", label: "GMT+00:00 Atlantic/Canary (WET)" },
  { value: "Atlantic/Faroe", label: "GMT+00:00 Atlantic/Faroe (WET)" },
  { value: "Atlantic/Madeira", label: "GMT+00:00 Atlantic/Madeira (WET)" },
  { value: "Atlantic/Reykjavik", label: "GMT+00:00 Atlantic/Reykjavik (GMT)" },
  { value: "Atlantic/St_Helena", label: "GMT+00:00 Atlantic/St Helena (GMT)" },
  { value: "Europe/Dublin", label: "GMT+00:00 Europe/Dublin (IST)" },
  { value: "Europe/Guernsey", label: "GMT+00:00 Europe/Guernsey (GMT)" },
  { value: "Europe/Isle_of_Man", label: "GMT+00:00 Europe/Isle of Man (GMT)" },
  { value: "Europe/Jersey", label: "GMT+00:00 Europe/Jersey (GMT)" },
  { value: "Europe/Lisbon", label: "GMT+00:00 Europe/Lisbon (WET)" },
  { value: "Europe/London", label: "GMT+00:00 Europe/London (GMT)" },
  { value: "Africa/Algiers", label: "GMT+01:00 Africa/Algiers (CET)" },
  { value: "Africa/Bangui", label: "GMT+01:00 Africa/Bangui (WAT)" },
  { value: "Africa/Brazzaville", label: "GMT+01:00 Africa/Brazzaville (WAT)" },
  { value: "Africa/Casablanca", label: "GMT+01:00 Africa/Casablanca (WET)" },
  { value: "Africa/Ceuta", label: "GMT+01:00 Africa/Ceuta (CET)" },
  { value: "Africa/Douala", label: "GMT+01:00 Africa/Douala (WAT)" },
  { value: "Africa/El_Aaiun", label: "GMT+01:00 Africa/El Aaiun" },
  { value: "Africa/Kinshasa", label: "GMT+01:00 Africa/Kinshasa (WAT)" },
  { value: "Africa/Lagos", label: "GMT+01:00 Africa/Lagos (WAT)" },
  { value: "Africa/Libreville", label: "GMT+01:00 Africa/Libreville (WAT)" },
  { value: "Africa/Luanda", label: "GMT+01:00 Africa/Luanda (WAT)" },
  { value: "Africa/Malabo", label: "GMT+01:00 Africa/Malabo (WAT)" },
  { value: "Africa/Ndjamena", label: "GMT+01:00 Africa/Ndjamena (WAT)" },
  { value: "Africa/Niamey", label: "GMT+01:00 Africa/Niamey (WAT)" },
  { value: "Africa/Porto-Novo", label: "GMT+01:00 Africa/Porto-Novo (WAT)" },
  { value: "Africa/Tunis", label: "GMT+01:00 Africa/Tunis (CET)" },
  { value: "Europe/Amsterdam", label: "GMT+01:00 Europe/Amsterdam (CET)" },
  { value: "Europe/Andorra", label: "GMT+01:00 Europe/Andorra (CET)" },
  { value: "Europe/Belgrade", label: "GMT+01:00 Europe/Belgrade (CET)" },
  { value: "Europe/Berlin", label: "GMT+01:00 Europe/Berlin (CET)" },
  { value: "Europe/Bratislava", label: "GMT+01:00 Europe/Bratislava (CET)" },
  { value: "Europe/Brussels", label: "GMT+01:00 Europe/Brussels (CET)" },
  { value: "Europe/Budapest", label: "GMT+01:00 Europe/Budapest (CET)" },
  { value: "Europe/Busingen", label: "GMT+01:00 Europe/Busingen (CET)" },
  { value: "Europe/Copenhagen", label: "GMT+01:00 Europe/Copenhagen (CET)" },
  { value: "Europe/Gibraltar", label: "GMT+01:00 Europe/Gibraltar (CET)" },
  { value: "Europe/Ljubljana", label: "GMT+01:00 Europe/Ljubljana (CET)" },
  { value: "Europe/Luxembourg", label: "GMT+01:00 Europe/Luxembourg (CET)" },
  { value: "Europe/Madrid", label: "GMT+01:00 Europe/Madrid (CET)" },
  { value: "Europe/Malta", label: "GMT+01:00 Europe/Malta (CET)" },
  { value: "Europe/Monaco", label: "GMT+01:00 Europe/Monaco (CET)" },
  { value: "Europe/Oslo", label: "GMT+01:00 Europe/Oslo (CET)" },
  { value: "Europe/Paris", label: "GMT+01:00 Europe/Paris (CET)" },
  { value: "Europe/Podgorica", label: "GMT+01:00 Europe/Podgorica (CET)" },
  { value: "Europe/Prague", label: "GMT+01:00 Europe/Prague (CET)" },
  { value: "Europe/Rome", label: "GMT+01:00 Europe/Rome (CET)" },
  { value: "Europe/San_Marino", label: "GMT+01:00 Europe/San Marino (CET)" },
  { value: "Europe/Sarajevo", label: "GMT+01:00 Europe/Sarajevo (CET)" },
  { value: "Europe/Skopje", label: "GMT+01:00 Europe/Skopje (CET)" },
  { value: "Europe/Stockholm", label: "GMT+01:00 Europe/Stockholm (CET)" },
  { value: "Europe/Tirane", label: "GMT+01:00 Europe/Tirane (CET)" },
  { value: "Europe/Vaduz", label: "GMT+01:00 Europe/Vaduz (CET)" },
  { value: "Europe/Vatican", label: "GMT+01:00 Europe/Vatican (CET)" },
  { value: "Europe/Vienna", label: "GMT+01:00 Europe/Vienna (CET)" },
  { value: "Europe/Warsaw", label: "GMT+01:00 Europe/Warsaw (CET)" },
  { value: "Europe/Zagreb", label: "GMT+01:00 Europe/Zagreb (CET)" },
  { value: "Europe/Zurich", label: "GMT+01:00 Europe/Zurich (CET)" },
  { value: "Africa/Blantyre", label: "GMT+02:00 Africa/Blantyre (CAT)" },
  { value: "Africa/Bujumbura", label: "GMT+02:00 Africa/Bujumbura (CAT)" },
  { value: "Africa/Cairo", label: "GMT+02:00 Africa/Cairo (EET)" },
  { value: "Africa/Gaborone", label: "GMT+02:00 Africa/Gaborone (CAT)" },
  { value: "Africa/Harare", label: "GMT+02:00 Africa/Harare (CAT)" },
  { value: "Africa/Johannesburg", label: "GMT+02:00 Africa/Johannesburg (SAST)" },
  { value: "Africa/Juba", label: "GMT+02:00 Africa/Juba (EAT)" },
  { value: "Africa/Khartoum", label: "GMT+02:00 Africa/Khartoum (EAT)" },
  { value: "Africa/Kigali", label: "GMT+02:00 Africa/Kigali (CAT)" },
  { value: "Africa/Lubumbashi", label: "GMT+02:00 Africa/Lubumbashi (CAT)" },
  { value: "Africa/Lusaka", label: "GMT+02:00 Africa/Lusaka (CAT)" },
  { value: "Africa/Maputo", label: "GMT+02:00 Africa/Maputo (CAT)" },
  { value: "Africa/Maseru", label: "GMT+02:00 Africa/Maseru (SAST)" },
  { value: "Africa/Mbabane", label: "GMT+02:00 Africa/Mbabane (SAST)" },
  { value: "Africa/Tripoli", label: "GMT+02:00 Africa/Tripoli (EET)" },
  { value: "Africa/Windhoek", label: "GMT+02:00 Africa/Windhoek (WAT)" },
  { value: "Asia/Beirut", label: "GMT+02:00 Asia/Beirut (EET)" },
  { value: "Asia/Famagusta", label: "GMT+02:00 Asia/Famagusta (EET)" },
  { value: "Asia/Gaza", label: "GMT+02:00 Asia/Gaza (EET)" },
  { value: "Asia/Hebron", label: "GMT+02:00 Asia/Hebron (EET)" },
  { value: "Asia/Jerusalem", label: "GMT+02:00 Asia/Jerusalem (IST)" },
  { value: "Asia/Nicosia", label: "GMT+02:00 Asia/Nicosia (EET)" },
  { value: "Europe/Athens", label: "GMT+02:00 Europe/Athens (EET)" },
  { value: "Europe/Bucharest", label: "GMT+02:00 Europe/Bucharest (EET)" },
  { value: "Europe/Chisinau", label: "GMT+02:00 Europe/Chisinau (EET)" },
  { value: "Europe/Helsinki", label: "GMT+02:00 Europe/Helsinki (EET)" },
  { value: "Europe/Kaliningrad", label: "GMT+02:00 Europe/Kaliningrad (EET)" },
  { value: "Europe/Kiev", label: "GMT+02:00 Europe/Kiev (EET)" },
  { value: "Europe/Mariehamn", label: "GMT+02:00 Europe/Mariehamn (EET)" },
  { value: "Europe/Nicosia", label: "GMT+02:00 Europe/Nicosia (EET)" },
  { value: "Europe/Riga", label: "GMT+02:00 Europe/Riga (EET)" },
  { value: "Europe/Sofia", label: "GMT+02:00 Europe/Sofia (EET)" },
  { value: "Europe/Tallinn", label: "GMT+02:00 Europe/Tallinn (EET)" },
  { value: "Europe/Uzhgorod", label: "GMT+02:00 Europe/Uzhgorod (EET)" },
  { value: "Europe/Vilnius", label: "GMT+02:00 Europe/Vilnius (EET)" },
  { value: "Europe/Zaporozhye", label: "GMT+02:00 Europe/Zaporozhye (EET)" },
  { value: "Africa/Addis_Ababa", label: "GMT+03:00 Africa/Addis Ababa (EAT)" },
  { value: "Africa/Asmara", label: "GMT+03:00 Africa/Asmara (EAT)" },
  { value: "Africa/Dar_es_Salaam", label: "GMT+03:00 Africa/Dar es Salaam (EAT)" },
  { value: "Africa/Djibouti", label: "GMT+03:00 Africa/Djibouti (EAT)" },
  { value: "Africa/Kampala", label: "GMT+03:00 Africa/Kampala (EAT)" },
  { value: "Africa/Mogadishu", label: "GMT+03:00 Africa/Mogadishu (EAT)" },
  { value: "Africa/Nairobi", label: "GMT+03:00 Africa/Nairobi (EAT)" },
  { value: "Antarctica/Syowa", label: "GMT+03:00 Antarctica/Syowa" },
  { value: "Asia/Aden", label: "GMT+03:00 Asia/Aden (AST)" },
  { value: "Asia/Amman", label: "GMT+03:00 Asia/Amman (AST)" },
  { value: "Asia/Baghdad", label: "GMT+03:00 Asia/Baghdad (AST)" },
  { value: "Asia/Bahrain", label: "GMT+03:00 Asia/Bahrain (AST)" },
  { value: "Asia/Damascus", label: "GMT+03:00 Asia/Damascus (AST)" },
  { value: "Asia/Istanbul", label: "GMT+03:00 Asia/Istanbul (TRT)" },
  { value: "Asia/Kuwait", label: "GMT+03:00 Asia/Kuwait (AST)" },
  { value: "Asia/Qatar", label: "GMT+03:00 Asia/Qatar (AST)" },
  { value: "Asia/Riyadh", label: "GMT+03:00 Asia/Riyadh (AST)" },
  { value: "Europe/Istanbul", label: "GMT+03:00 Europe/Istanbul (TRT)" },
  { value: "Europe/Kirov", label: "GMT+03:00 Europe/Kirov" },
  { value: "Europe/Minsk", label: "GMT+03:00 Europe/Minsk (FET)" },
  { value: "Europe/Moscow", label: "GMT+03:00 Europe/Moscow (MSK)" },
  { value: "Europe/Simferopol", label: "GMT+03:00 Europe/Simferopol (MSK)" },
  { value: "Europe/Volgograd", label: "GMT+03:00 Europe/Volgograd" },
  { value: "Indian/Antananarivo", label: "GMT+03:00 Indian/Antananarivo (EAT)" },
  { value: "Indian/Comoro", label: "GMT+03:00 Indian/Comoro (EAT)" },
  { value: "Indian/Mayotte", label: "GMT+03:00 Indian/Mayotte (EAT)" },
  { value: "Asia/Tehran", label: "GMT+03:30 Asia/Tehran (IRST)" },
  { value: "Asia/Baku", label: "GMT+04:00 Asia/Baku (AZT)" },
  { value: "Asia/Dubai", label: "GMT+04:00 Asia/Dubai (GST)" },
  { value: "Asia/Muscat", label: "GMT+04:00 Asia/Muscat (GST)" },
  { value: "Asia/Tbilisi", label: "GMT+04:00 Asia/Tbilisi (GET)" },
  { value: "Asia/Yerevan", label: "GMT+04:00 Asia/Yerevan (AMT)" },
  { value: "Europe/Astrakhan", label: "GMT+04:00 Europe/Astrakhan" },
  { value: "Europe/Samara", label: "GMT+04:00 Europe/Samara" },
  { value: "Europe/Saratov", label: "GMT+04:00 Europe/Saratov" },
  { value: "Europe/Ulyanovsk", label: "GMT+04:00 Europe/Ulyanovsk" },
  { value: "Indian/Mahe", label: "GMT+04:00 Indian/Mahe (SCT)" },
  { value: "Indian/Mauritius", label: "GMT+04:00 Indian/Mauritius (MUT)" },
  { value: "Indian/Reunion", label: "GMT+04:00 Indian/Reunion (RET)" },
  { value: "Asia/Kabul", label: "GMT+04:30 Asia/Kabul (AFT)" },
  { value: "Antarctica/Mawson", label: "GMT+05:00 Antarctica/Mawson" },
  { value: "Asia/Aqtau", label: "GMT+05:00 Asia/Aqtau (AQTT)" },
  { value: "Asia/Aqtobe", label: "GMT+05:00 Asia/Aqtobe (AQTT)" },
  { value: "Asia/Ashgabat", label: "GMT+05:00 Asia/Ashgabat (TMT)" },
  { value: "Asia/Atyrau", label: "GMT+05:00 Asia/Atyrau" },
  { value: "Asia/Dushanbe", label: "GMT+05:00 Asia/Dushanbe (TJT)" },
  { value: "Asia/Karachi", label: "GMT+05:00 Asia/Karachi (PKT)" },
  { value: "Asia/Oral", label: "GMT+05:00 Asia/Oral" },
  { value: "Asia/Qyzylorda", label: "GMT+05:00 Asia/Qyzylorda" },
  { value: "Asia/Samarkand", label: "GMT+05:00 Asia/Samarkand (UZT)" },
  { value: "Asia/Tashkent", label: "GMT+05:00 Asia/Tashkent (UZT)" },
  { value: "Asia/Yekaterinburg", label: "GMT+05:00 Asia/Yekaterinburg (YEKT)" },
  { value: "Indian/Kerguelen", label: "GMT+05:00 Indian/Kerguelen" },
  { value: "Indian/Maldives", label: "GMT+05:00 Indian/Maldives (MVT)" },
  { value: "Asia/Colombo", label: "GMT+05:30 Asia/Colombo (IST)" },
  { value: "Asia/Kolkata", label: "GMT+05:30 Asia/Kolkata (IST)" },
  { value: "Asia/Kathmandu", label: "GMT+05:45 Asia/Kathmandu (NPT)" },
  { value: "Antarctica/Vostok", label: "GMT+06:00 Antarctica/Vostok" },
  { value: "Asia/Almaty", label: "GMT+06:00 Asia/Almaty (ALMT)" },
  { value: "Asia/Bishkek", label: "GMT+06:00 Asia/Bishkek (KGT)" },
  { value: "Asia/Dhaka", label: "GMT+06:00 Asia/Dhaka (BST)" },
  { value: "Asia/Omsk", label: "GMT+06:00 Asia/Omsk (OMST)" },
  { value: "Asia/Qostanay", label: "GMT+06:00 Asia/Qostanay" },
  { value: "Asia/Thimphu", label: "GMT+06:00 Asia/Thimphu (BTT)" },
  { value: "Asia/Urumqi", label: "GMT+06:00 Asia/Urumqi (XJT)" },
  { value: "Indian/Chagos", label: "GMT+06:00 Indian/Chagos (IOT)" },
  { value: "Asia/Yangon", label: "GMT+06:30 Asia/Yangon (MMT)" },
  { value: "Indian/Cocos", label: "GMT+06:30 Indian/Cocos (CCT)" },
  { value: "Antarctica/Davis", label: "GMT+07:00 Antarctica/Davis" },
  { value: "Asia/Bangkok", label: "GMT+07:00 Asia/Bangkok (ICT)" },
  { value: "Asia/Barnaul", label: "GMT+07:00 Asia/Barnaul" },
  { value: "Asia/Ho_Chi_Minh", label: "GMT+07:00 Asia/Ho Chi Minh (ICT)" },
  { value: "Asia/Hovd", label: "GMT+07:00 Asia/Hovd (HOVT)" },
  { value: "Asia/Jakarta", label: "GMT+07:00 Asia/Jakarta (WIB)" },
  { value: "Asia/Krasnoyarsk", label: "GMT+07:00 Asia/Krasnoyarsk (KRAT)" },
  { value: "Asia/Novokuznetsk", label: "GMT+07:00 Asia/Novokuznetsk" },
  { value: "Asia/Novosibirsk", label: "GMT+07:00 Asia/Novosibirsk (NOVT)" },
  { value: "Asia/Phnom_Penh", label: "GMT+07:00 Asia/Phnom Penh (ICT)" },
  { value: "Asia/Pontianak", label: "GMT+07:00 Asia/Pontianak (WIB)" },
  { value: "Asia/Tomsk", label: "GMT+07:00 Asia/Tomsk" },
  { value: "Asia/Vientiane", label: "GMT+07:00 Asia/Vientiane (ICT)" },
  { value: "Indian/Christmas", label: "GMT+07:00 Indian/Christmas (CXT)" },
  { value: "Asia/Brunei", label: "GMT+08:00 Asia/Brunei (BNT)" },
  { value: "Asia/Choibalsan", label: "GMT+08:00 Asia/Choibalsan (CHOT)" },
  { value: "Asia/Hong_Kong", label: "GMT+08:00 Asia/Hong Kong (HKT)" },
  { value: "Asia/Irkutsk", label: "GMT+08:00 Asia/Irkutsk (IRKT)" },
  { value: "Asia/Kuala_Lumpur", label: "GMT+08:00 Asia/Kuala Lumpur (MYT)" },
  { value: "Asia/Kuching", label: "GMT+08:00 Asia/Kuching (MYT)" },
  { value: "Asia/Macau", label: "GMT+08:00 Asia/Macau (CST)" },
  { value: "Asia/Makassar", label: "GMT+08:00 Asia/Makassar (WITA)" },
  { value: "Asia/Manila", label: "GMT+08:00 Asia/Manila (PHT)" },
  { value: "Asia/Shanghai", label: "GMT+08:00 Asia/Shanghai (CST)" },
  { value: "Asia/Singapore", label: "GMT+08:00 Asia/Singapore (SGT)" },
  { value: "Asia/Taipei", label: "GMT+08:00 Asia/Taipei (CST)" },
  { value: "Asia/Ulaanbaatar", label: "GMT+08:00 Asia/Ulaanbaatar (ULAT)" },
  { value: "Australia/Perth", label: "GMT+08:00 Australia/Perth (AWST)" },
  { value: "Australia/Eucla", label: "GMT+08:45 Australia/Eucla" },
  { value: "Asia/Chita", label: "GMT+09:00 Asia/Chita (YAKT)" },
  { value: "Asia/Dili", label: "GMT+09:00 Asia/Dili (TLT)" },
  { value: "Asia/Jayapura", label: "GMT+09:00 Asia/Jayapura (WIT)" },
  { value: "Asia/Khandyga", label: "GMT+09:00 Asia/Khandyga" },
  { value: "Asia/Pyongyang", label: "GMT+09:00 Asia/Pyongyang (KST)" },
  { value: "Asia/Seoul", label: "GMT+09:00 Asia/Seoul (KST)" },
  { value: "Asia/Tokyo", label: "GMT+09:00 Asia/Tokyo (JST)" },
  { value: "Asia/Yakutsk", label: "GMT+09:00 Asia/Yakutsk (YAKT)" },
  { value: "Pacific/Palau", label: "GMT+09:00 Pacific/Palau (PWT)" },
  { value: "Australia/Adelaide", label: "GMT+09:30 Australia/Adelaide (ACST)" },
  { value: "Australia/Broken_Hill", label: "GMT+09:30 Australia/Broken Hill (ACST)" },
  { value: "Australia/Darwin", label: "GMT+09:30 Australia/Darwin (ACST)" },
  { value: "Antarctica/DumontDUrville", label: "GMT+10:00 Antarctica/DumontDUrville" },
  { value: "Asia/Ust-Nera", label: "GMT+10:00 Asia/Ust-Nera" },
  { value: "Asia/Vladivostok", label: "GMT+10:00 Asia/Vladivostok (VLAT)" },
  { value: "Australia/Brisbane", label: "GMT+10:00 Australia/Brisbane (AEST)" },
  { value: "Australia/Currie", label: "GMT+10:00 Australia/Currie (AEST)" },
  { value: "Australia/Hobart", label: "GMT+10:00 Australia/Hobart (AEST)" },
  { value: "Australia/Lindeman", label: "GMT+10:00 Australia/Lindeman (AEST)" },
  { value: "Australia/Melbourne", label: "GMT+10:00 Australia/Melbourne (AEST)" },
  { value: "Australia/Sydney", label: "GMT+10:00 Australia/Sydney (AEST)" },
  { value: "Pacific/Chuuk", label: "GMT+10:00 Pacific/Chuuk (CHUT)" },
  { value: "Pacific/Guam", label: "GMT+10:00 Pacific/Guam (ChST)" },
  { value: "Pacific/Port_Moresby", label: "GMT+10:00 Pacific/Port Moresby (PGT)" },
  { value: "Pacific/Saipan", label: "GMT+10:00 Pacific/Saipan (ChST)" },
  { value: "Australia/Lord_Howe", label: "GMT+10:30 Australia/Lord Howe" },
  { value: "Antarctica/Casey", label: "GMT+11:00 Antarctica/Casey" },
  { value: "Antarctica/Macquarie", label: "GMT+11:00 Antarctica/Macquarie" },
  { value: "Asia/Magadan", label: "GMT+11:00 Asia/Magadan (MAGT)" },
  { value: "Asia/Sakhalin", label: "GMT+11:00 Asia/Sakhalin (SAKT)" },
  { value: "Asia/Srednekolymsk", label: "GMT+11:00 Asia/Srednekolymsk" },
  { value: "Pacific/Bougainville", label: "GMT+11:00 Pacific/Bougainville" },
  { value: "Pacific/Efate", label: "GMT+11:00 Pacific/Efate (VUT)" },
  { value: "Pacific/Guadalcanal", label: "GMT+11:00 Pacific/Guadalcanal (SBT)" },
  { value: "Pacific/Kosrae", label: "GMT+11:00 Pacific/Kosrae (KOST)" },
  { value: "Pacific/Norfolk", label: "GMT+11:00 Pacific/Norfolk (NFT)" },
  { value: "Pacific/Noumea", label: "GMT+11:00 Pacific/Noumea (NCT)" },
  { value: "Pacific/Pohnpei", label: "GMT+11:00 Pacific/Pohnpei (PONT)" },
  { value: "Asia/Anadyr", label: "GMT+12:00 Asia/Anadyr (ANAT)" },
  { value: "Asia/Kamchatka", label: "GMT+12:00 Asia/Kamchatka (PETT)" },
  { value: "Pacific/Auckland", label: "GMT+12:00 Pacific/Auckland (NZST)" },
  { value: "Pacific/Fiji", label: "GMT+12:00 Pacific/Fiji (FJT)" },
  { value: "Pacific/Funafuti", label: "GMT+12:00 Pacific/Funafuti (TVT)" },
  { value: "Pacific/Kwajalein", label: "GMT+12:00 Pacific/Kwajalein (MHT)" },
  { value: "Pacific/Majuro", label: "GMT+12:00 Pacific/Majuro (MHT)" },
  { value: "Pacific/Nauru", label: "GMT+12:00 Pacific/Nauru (NRT)" },
  { value: "Pacific/Tarawa", label: "GMT+12:00 Pacific/Tarawa (GILT)" },
  { value: "Pacific/Wake", label: "GMT+12:00 Pacific/Wake (WAKT)" },
  { value: "Pacific/Wallis", label: "GMT+12:00 Pacific/Wallis (WFT)" },
  { value: "Pacific/Chatham", label: "GMT+12:45 Pacific/Chatham (NZCT)" },
  { value: "Pacific/Apia", label: "GMT+13:00 Pacific/Apia (WST)" },
  { value: "Pacific/Enderbury", label: "GMT+13:00 Pacific/Enderbury" },
  { value: "Pacific/Fakaofo", label: "GMT+13:00 Pacific/Fakaofo (TKT)" },
  { value: "Pacific/Tongatapu", label: "GMT+13:00 Pacific/Tongatapu (TOT)" },
  { value: "Pacific/Kiritimati", label: "GMT+14:00 Pacific/Kiritimati (LINT)" },
];
